dvpOAuth/__init__.py,sha256=xfEEC09e6OnUaA8Bq1mBPWl85iIlXpmCJdkMIfnkecs,163
dvpOAuth/class_OAuth.py,sha256=r9gZ2EyKw_MYkBCZh-wwEuIJmsrcl1hDk7RZN4yF7lg,13889
dvpOAuth/error.py,sha256=Y3BjsevsSGMDVVdn6ztiQMcGNtB6lySkNPoL7y4BT-Q,131
dvpOAuth/util.py,sha256=A7ZoIm1mjYwD4X9aommSZRYpi9ZidUuqMd2OYf1Ee64,743
dvpOAuth-0.0.14.dist-info/LICENSE,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
dvpOAuth-0.0.14.dist-info/METADATA,sha256=-7YRE2_puS9XEnM4_Ux0Nq7r3SxNEi6-9t_n5VirVU4,992
dvpOAuth-0.0.14.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
dvpOAuth-0.0.14.dist-info/top_level.txt,sha256=14UgmlstFHh0UvlWIljRlFO26u2OesXzFC8SsWFZRmw,9
dvpOAuth-0.0.14.dist-info/RECORD,,
